In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to Tensors

### Creating tensors

In [2]:
# Scalar
scalar = torch.tensor(4)
scalar

tensor(4)

In [3]:
scalar.ndim # scalar has no dimensions

0

In [4]:
scalar.item() # Get tensor back as python int

4

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [3, 6, 9, 10],
                        [2, 4, 5, 11]]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 3,  6,  9, 10],
         [ 2,  4,  5, 11]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape # 1 3X3 tensor

torch.Size([1, 3, 4])

In [15]:
TENSOR[0]

tensor([[ 1,  2,  3,  4],
        [ 3,  6,  9, 10],
        [ 2,  4,  5, 11]])

### Random Tensors

In [16]:
# Create a random tensor of size(3, 4)
random_tensor = torch.rand(3, 4)
random_tensor
# torch.rand: Interval (0, 1) (Always positive)
# torch.randn: All real numbers (-inf to +inf)

tensor([[0.3842, 0.4224, 0.7283, 0.5844],
        [0.1665, 0.4714, 0.6508, 0.9925],
        [0.0403, 0.2461, 0.9451, 0.3405]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(3, 224, 224) # color channels, height, weight
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [19]:
# create a tensor of all zeros
zeros = torch.zeros(3,4) # useful to create masks
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [22]:
# Use torch.range (deprecated), use torch.arange()
one_to_ten = torch.arange(start=0, end=10, step=1) # 0 to 9, end is exclusive, start is inclusize
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # float32 (single precision) or float16 (half precision)
                               device=None, # what device the tensor is created
                               requires_grad=False) # Whether or not to track gradients with this tensor's operations
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
(float_16_tensor * float_32_tensor).dtype # Caveat: No error

torch.float32

In [27]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
int_32_tensor * float_32_tensor # Caveat: No error

tensor([ 9., 36., 81.])

### Getting information from Tensors
1. Tensors not right datatype - to do get datatype, use `tensor.dtype`
2. Tensor not right shape - to get shape, use `tensor.shape`
3. Tensor not on the right device - to get device from a tensor, use `tensor.device`

In [29]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6160, 0.6172, 0.7189, 0.2895],
        [0.9521, 0.1799, 0.9111, 0.3053],
        [0.7720, 0.3524, 0.7879, 0.6242]])

In [30]:
# Find details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # or some_tensor.size()
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6160, 0.6172, 0.7189, 0.2895],
        [0.9521, 0.1799, 0.9111, 0.3053],
        [0.7720, 0.3524, 0.7879, 0.6242]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication (element-wise)
* ZeroDivisionError* MAtrix multiplication

In [31]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Try out pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication
1. Element-wise
2. Matrix multiplication

Rules:
1. Inner dimensions must match:
* `(3, 2) @ (2, 3)` will work
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
2. Resulting matrix has the shape of the outer dimensions:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [35]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 5))

tensor([[2.0156, 1.7184, 1.6197, 1.3562, 1.1531],
        [1.6547, 1.5665, 1.5212, 0.9486, 0.7074]])

In [36]:
# element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 700 µs, sys: 0 ns, total: 700 µs
Wall time: 4.64 ms


tensor(14)

In [38]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.66 ms, sys: 0 ns, total: 1.66 ms
Wall time: 4.79 ms


### One of the most common errors in deep learning: shape errors

In [39]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [40]:
# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (its an alias for writing less code)

# To fix tensor shape, we can manipulate shape of our tensors using a `transpose`
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [41]:
# matrix multiplication works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- Inner dimensions must match")
print("Output:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- Inner dimensions must match
Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Tensor Aggregation (min, max, sum, etc)

In [42]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [43]:
# find min
torch.min(x), x.sum()

(tensor(1), tensor(460))

In [44]:
# find max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [45]:
# find mean

# torch.mean(x) # Error! RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [46]:
# find sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding positional min and max

In [47]:
# find position in tensor which has minimum value with argmin --> returns index position
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [48]:
# find position in tensor which has maximum value with argmin --> returns index position
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

## Reshape, stack, squeeze, unsqueeze tensors

* Reshape - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stack - Combine multiple tensors on top of each other (vstack) or side-by-side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [49]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# Changing z changes x (because view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [53]:
# Stack tensors on top of each other
# x_stacked = torch.stack([x, x, x, x], dim=0) # vertical
x_stacked = torch.stack([x, x, x, x], dim=1) # horizontal
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [54]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [56]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
# torch.permute rearranges the dimensions of the target tensor in a specified order --> returns a view
x_original = torch.rand(224, 224, 3) # H, W, C
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = torch.permute(x_original, dims=(2, 0, 1)) # C, H, W
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [58]:
# x_permuted will share the same memory as x_original as its just a view
x_original[0, 0, 0] = 72138
print(f"Before: x_original = {x_original[0, 0, 0]}, x_permuted = {x_permuted[0, 0, 0]}")
x_permuted[0, 0, 0] = 22
print(f"After: x_original = {x_original[0, 0, 0]}, x_permuted = {x_permuted[0, 0, 0]}")

Before: x_original = 72138.0, x_permuted = 72138.0
After: x_original = 22.0, x_permuted = 22.0


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [59]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
# Lets index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
# Lets index on the middle brack (dim = 1)
x[0][0] # or x[0, 0]

tensor([1, 2, 3])

In [62]:
# Lets index on the most inner bracket (dim = 2)
x[0, 2, 2]

tensor(9)

In [63]:
# You can also use ":" to select "all" of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [64]:
# Get all values of 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [65]:
# Get all values of 0th dim but only the 1 index of the 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [66]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

In [67]:
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

* NumPy -> PyTorch: `torch.from_numpy(ndarray)
* PyTorch -> NumPy: `torch.Tensor.numpy()`

Default numpy datatype: float64
Default tensor datatype: float32

In [68]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, Pytorch reflects numpy's default datatype float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
# Change the value of array, does not change value of `tensor`
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [70]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

To reduce the randomness in NN and PyTorch, comes the concept of random seed. Essentially, what the random seed does is flavor the randomness.

In [71]:
# Create 2 random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7973, 0.9478, 0.1872, 0.7396],
        [0.8289, 0.9518, 0.1864, 0.3649],
        [0.1158, 0.7869, 0.5655, 0.8400]])
tensor([[0.5932, 0.8882, 0.1047, 0.7741],
        [0.7840, 0.5944, 0.1408, 0.9191],
        [0.3858, 0.9784, 0.4370, 0.7895]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [72]:
# Lets make random but reproducible tensors
# Set random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # use this everything when you need to create randomness
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## GPU Access

In [73]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [74]:
torch.cuda.is_available()

False

In [75]:
# Setup a device agnostic code
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cpu')

In [76]:
# Count the number of devices
torch.cuda.device_count()

0

## Putting tensors (and models) on GPU

In [77]:
# create a tensor (default on cpu)
tensor = torch.tensor([1, 2, 3])
# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [78]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3]) cpu


### Moving tensors to CPU

In [79]:
# tensor_on_gpu.numpy() # TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [80]:
tensor_on_gpu

tensor([1, 2, 3])

## Exercises

In [81]:
import torch
import numpy as np

In [82]:
# Create a random tensor with shape (7, 7)
random_tensor1 = torch.rand(7,7)
random_tensor1

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [83]:
# Perform a matrix multiplication on the tensor with another random tensor with shape (1, 7)
random_tensor2 = torch.rand(1,7)
random_tensor1 @ random_tensor2.T # (7,1)

tensor([[1.9625],
        [1.0950],
        [0.9967],
        [1.8910],
        [1.9205],
        [1.0674],
        [1.6949]])

In [84]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor3 = torch.rand(7,7)
random_tensor3, random_tensor3.shape

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 torch.Size([7, 7]))

In [85]:
torch.manual_seed(RANDOM_SEED)
random_tensor4 = torch.rand(1,7)
random_tensor4, random_tensor4.shape

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 torch.Size([1, 7]))

In [86]:
output = random_tensor3 @ random_tensor4.T
output, output.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [87]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
torch.cuda.manual_seed(1234)

In [88]:
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

random_tensor6 = torch.rand(2,3).to(device)
random_tensor7 = torch.rand(2,3).to(device)
random_tensor6, random_tensor7

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [89]:
out = random_tensor6 @ random_tensor7.T
out, out.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [90]:
# Find the maximum and minimum values of the output
max_val = torch.max(out)
min_val = torch.min(out)
max_val, min_val

(tensor(0.5617), tensor(0.3647))

In [91]:
# Find the maximum and minimum index values of the output
max_val_idx = torch.argmax(out)
min_val_idx = torch.argmin(out)
max_val_idx, min_val_idx

(tensor(3), tensor(0))

In [92]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions
# removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the
# second tensor and it's shape.
torch.manual_seed(7)
random_tensor8 = torch.rand(1, 1, 1, 10)
random_tensor9 = torch.squeeze(random_tensor8)
random_tensor8, random_tensor8.shape, random_tensor9, random_tensor9.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))